# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9793e9c8f082a32f6a3d97a6d14e498b29d9f2732e6779929f90164cf730036c1da3c83634f72e361b277eed2817876fffda8a5f68ef5dcb3cf0928b72272c2c

test:
  secret_key_base: dea6de58319e258e48ce505079e0e924eaaa09301ab2cade4aa157703f8a2393ec788a3fc306efabe6923546486866544b052ad819b94ba67e93cc525485c719

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
